# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_pacbiowdlR_wrappers", use_symbols = TRUE, package_name = "pacbiowdlR")

#' @usage NULL
#' @useDynLib pacbiowdlR, .registration = TRUE
NULL

read_bed <- function(bed_path, bw_path) .Call(wrap__read_bed, bed_path, bw_path)


# nolint end
